# Generated by Django 3.1.7 on 2021-04-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status_name',
            new_name='name',
        ),
    ]
